/**
 * Opaque, single-use tokens for email verification and password reset
 * links — docs/13-SECURITY.md §2: "Single-use token... hashed at rest,
 * invalidated on use." Not passwords: these are high-entropy random
 * values generated by the server, never chosen or guessable by a human,
 * so a fast digest (SHA-256) is the right tool — Argon2id's deliberate
 * slowness (`lib/password.ts`) exists to blunt *offline guessing* of a
 * low-entropy human-chosen secret, which doesn't apply here.
 */
import { createHash, randomBytes } from "node:crypto";

/** A URL-safe random token to embed in a verification/reset link. 32 bytes = 256 bits of entropy. */
export function generateOpaqueToken(byteLength = 32): string {
  return randomBytes(byteLength).toString("base64url");
}

/** The form actually stored in `VerificationToken.token` — never the raw token from `generateOpaqueToken`. */
export function hashOpaqueToken(token: string): string {
  return createHash("sha256").update(token, "utf8").digest("hex");
}
